import { Types } from 'mongoose';

// Pre-generate ObjectIds for consistent references
export const categoryIds = {
  // Main categories
  digitalTransformation: new Types.ObjectId(),
  webDevelopment: new Types.ObjectId(),
  businessTech: new Types.ObjectId(),
  devOps: new Types.ObjectId(),
  // Subcategories - Digital Transformation
  aiMl: new Types.ObjectId(),
  cloudComputing: new Types.ObjectId(),
  dataAnalytics: new Types.ObjectId(),
  // Subcategories - Web Development
  frontend: new Types.ObjectId(),
  backend: new Types.ObjectId(),
  fullStack: new Types.ObjectId(),
  // Subcategories - Business & Tech
  projectManagement: new Types.ObjectId(),
  leadership: new Types.ObjectId(),
  // Subcategories - DevOps
  ciCd: new Types.ObjectId(),
  security: new Types.ObjectId(),
};

export const categoriesData = [
  // Main Categories
  {
    _id: categoryIds.digitalTransformation,
    name: 'Digital Transformation',
    slug: 'digital-transformation',
    description: 'Master the technologies driving digital transformation in modern businesses. Learn AI, cloud computing, and data analytics.',
    icon: 'cpu',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    parent: null,
    order: 1,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Digital Transformation Courses | DX Education',
      metaDescription: 'Learn digital transformation skills including AI, machine learning, cloud computing, and data analytics.',
    },
  },
  {
    _id: categoryIds.webDevelopment,
    name: 'Web Development',
    slug: 'web-development',
    description: 'Build modern web applications with cutting-edge frameworks and technologies. From frontend to backend and everything in between.',
    icon: 'code',
    image: 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800',
    parent: null,
    order: 2,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Web Development Courses | DX Education',
      metaDescription: 'Master web development with React, Node.js, TypeScript, and modern full-stack technologies.',
    },
  },
  {
    _id: categoryIds.businessTech,
    name: 'Business & Technology',
    slug: 'business-technology',
    description: 'Bridge the gap between business strategy and technology implementation. Learn project management, leadership, and digital strategy.',
    icon: 'briefcase',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    parent: null,
    order: 3,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Business & Technology Courses | DX Education',
      metaDescription: 'Develop business and technology skills for the digital age. Project management, leadership, and strategy courses.',
    },
  },
  {
    _id: categoryIds.devOps,
    name: 'DevOps & Infrastructure',
    slug: 'devops-infrastructure',
    description: 'Learn DevOps practices, CI/CD pipelines, containerization, and cloud infrastructure management.',
    icon: 'server',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
    parent: null,
    order: 4,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'DevOps & Infrastructure Courses | DX Education',
      metaDescription: 'Master DevOps practices, Docker, Kubernetes, CI/CD, and cloud infrastructure.',
    },
  },

  // Subcategories - Digital Transformation
  {
    _id: categoryIds.aiMl,
    name: 'AI & Machine Learning',
    slug: 'ai-machine-learning',
    description: 'Explore artificial intelligence and machine learning concepts, algorithms, and practical applications.',
    icon: 'brain',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    parent: categoryIds.digitalTransformation,
    order: 1,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'AI & Machine Learning Courses | DX Education',
      metaDescription: 'Learn artificial intelligence and machine learning from beginner to advanced levels.',
    },
  },
  {
    _id: categoryIds.cloudComputing,
    name: 'Cloud Computing',
    slug: 'cloud-computing',
    description: 'Master cloud platforms including AWS, Azure, and Google Cloud. Learn architecture, deployment, and management.',
    icon: 'cloud',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800',
    parent: categoryIds.digitalTransformation,
    order: 2,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Cloud Computing Courses | DX Education',
      metaDescription: 'Learn AWS, Azure, Google Cloud and cloud architecture best practices.',
    },
  },
  {
    _id: categoryIds.dataAnalytics,
    name: 'Data Analytics',
    slug: 'data-analytics',
    description: 'Learn to analyze, visualize, and derive insights from data using modern tools and techniques.',
    icon: 'bar-chart',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    parent: categoryIds.digitalTransformation,
    order: 3,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Data Analytics Courses | DX Education',
      metaDescription: 'Master data analytics, visualization, and business intelligence tools.',
    },
  },

  // Subcategories - Web Development
  {
    _id: categoryIds.frontend,
    name: 'Frontend Development',
    slug: 'frontend-development',
    description: 'Build beautiful, responsive user interfaces with modern frontend frameworks and libraries.',
    icon: 'layout',
    image: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800',
    parent: categoryIds.webDevelopment,
    order: 1,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Frontend Development Courses | DX Education',
      metaDescription: 'Learn React, Vue, Angular, and modern frontend development techniques.',
    },
  },
  {
    _id: categoryIds.backend,
    name: 'Backend Development',
    slug: 'backend-development',
    description: 'Build robust server-side applications, APIs, and database systems.',
    icon: 'database',
    image: 'https://images.unsplash.com/photo-1518432031352-d6fc5c10da5a?w=800',
    parent: categoryIds.webDevelopment,
    order: 2,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Backend Development Courses | DX Education',
      metaDescription: 'Master Node.js, Python, databases, and API development.',
    },
  },
  {
    _id: categoryIds.fullStack,
    name: 'Full-Stack Development',
    slug: 'full-stack-development',
    description: 'Become a complete developer by mastering both frontend and backend technologies.',
    icon: 'layers',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800',
    parent: categoryIds.webDevelopment,
    order: 3,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Full-Stack Development Courses | DX Education',
      metaDescription: 'Learn full-stack development with modern frameworks and best practices.',
    },
  },

  // Subcategories - Business & Tech
  {
    _id: categoryIds.projectManagement,
    name: 'Project Management',
    slug: 'project-management',
    description: 'Learn agile methodologies, Scrum, and project management best practices for tech teams.',
    icon: 'clipboard-list',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    parent: categoryIds.businessTech,
    order: 1,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Project Management Courses | DX Education',
      metaDescription: 'Master Agile, Scrum, and project management for technology projects.',
    },
  },
  {
    _id: categoryIds.leadership,
    name: 'Tech Leadership',
    slug: 'tech-leadership',
    description: 'Develop leadership skills for managing technology teams and driving innovation.',
    icon: 'users',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800',
    parent: categoryIds.businessTech,
    order: 2,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Tech Leadership Courses | DX Education',
      metaDescription: 'Learn leadership skills for technology managers and executives.',
    },
  },

  // Subcategories - DevOps
  {
    _id: categoryIds.ciCd,
    name: 'CI/CD & Automation',
    slug: 'ci-cd-automation',
    description: 'Master continuous integration, continuous deployment, and automation tools.',
    icon: 'git-branch',
    image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800',
    parent: categoryIds.devOps,
    order: 1,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'CI/CD & Automation Courses | DX Education',
      metaDescription: 'Learn Jenkins, GitHub Actions, GitLab CI, and automation best practices.',
    },
  },
  {
    _id: categoryIds.security,
    name: 'Cloud Security',
    slug: 'cloud-security',
    description: 'Learn security best practices for cloud infrastructure and applications.',
    icon: 'shield',
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800',
    parent: categoryIds.devOps,
    order: 2,
    courseCount: 0,
    isActive: true,
    seo: {
      metaTitle: 'Cloud Security Courses | DX Education',
      metaDescription: 'Master cloud security, compliance, and security engineering practices.',
    },
  },
];
